#!/bin/bash
image: registry.git.rwth-aachen.de/ebc/ebc_intern/dymola-docker:miniconda-latest

stages:
    - CheckSettings
    - build
    - HTMLCheck
    - deploy
    - openMR
    - post
    - StyleCheck
    - Check
    - Simulate
    - RegressionTest

variables:
    TARGET_BRANCH: master
    Newbranch: "Correct_HTML_$TARGET_BRANCH"
    StyleModel: AixLib.Airflow.Multizone.DoorDiscretizedOpen
	

include:
    - project: 'EBC/EBC_all/gitlab_ci/templates'
    - file: 'ci-tests/CheckConfiguration/check_settings.gitlab-ci.yml'
    - project: 'EBC/EBC_all/gitlab_ci/templates'
    - file: 'ci-tests/SyntaxTests/html_check.gitlab-ci.yml'
    - project: 'EBC/EBC_all/gitlab_ci/templates'
    - file: 'ci-tests/SyntaxTests/style_check.gitlab-ci.yml'
    - project: 'EBC/EBC_all/gitlab_ci/templates'
    - file: 'ci-tests/UnitTests/check_model.gitlab-ci.yml'
    - project: 'EBC/EBC_all/gitlab_ci/templates'
    - file: 'ci-tests/UnitTests/regression_test.gitlac-ci.yml'
    - project: 'EBC/EBC_all/gitlab_ci/templates'
    - file: 'ci-tests/UnitTests/simulate_model.gitlab-ci.yml'
	