#!/bin/bash

stages:
    - Simulate
    
.Simulate_Changed_Job:
    stage: Simulate
    before_script:
        - Xvfb :77 -extension RANDR -extension GLX & export DISPLAY=:77.0 &&
        - export PIP_CACHE_DIR="/opt/cache/pip"
        - source activate python36  
        - python -V               # Print out python version for debugging
        - export PYTHONIOENCODING=utf-8 # just in case
    script:
        - model=$(git diff --raw --diff-filter=AMT HEAD^1)
        - echo $model >  bin/03_WhiteLists/changedmodels.txt
        - python bin/02_CITests/UnitTests/CheckPackages/validatetest.py -s "${AixLib_package}" -p AixLib/package.mo --SimulateExamples -CM -DS ${DymolaVersion}
    artifacts:
        when: on_failure
        paths:
            - AixLib/${AixLib_package} -log.txt
            - AixLib/${AixLib_package} -Errorlog.txt
        expire_in: 7 day 
    except:
        - external_pull_requests
        - IBPSA_Merge 
    only:
        variables:
            - $CI_COMMIT_MESSAGE !~ /Correct HTML Code/  
            - $CI_COMMIT_MESSAGE  !~ /Trigger CI - Update reference results/ 
            - $CI_COMMIT_MESSAGE  !~ /Trigger CI - give different reference results/
        changes:
            - AixLib/${package}/**/* 
            
    retry:
        max: 2
        when: runner_system_failure  

        
Simulate_Airflow_Changed_model:
    variables:
        AixLib_package: AixLib.Airflow
        package: Airflow
    extends: .Simulate_Changed_Job 
    
   
Simulate_BoundaryConditions_Changed_model:
    variables:
        AixLib_package: AixLib.BoundaryConditions
        package: BoundaryConditions
    extends: .Simulate_Changed_Job 
    
Simulate_Controls_Changed_model:
    variables:
        AixLib_package: AixLib.Controls
        package: Controls
    extends: .Simulate_Changed_Job 
    
   
Simulate_Electrical_Changed_model:
    variables:
        AixLib_package: AixLib.Electrical
        package: Electrical
    extends: .Simulate_Changed_Job 
    
            
Simulate_Fluid_Changed_model:
    variables:
        AixLib_package: AixLib.Fluid
        package: Fluid
    extends: .Simulate_Changed_Job 
    
            
Simulate_Media_Changed_model:
    variables:
        AixLib_package: AixLib.Media
        package: Media
    extends: .Simulate_Changed_Job 
    
   

Simulate_ThermalZones_Changed_model:
    variables:
        AixLib_package: AixLib.ThermalZones
        package: ThermalZones
    extends: .Simulate_Changed_Job 
    
 