#!/bin/bash

stages:
    - RegressionTest

    
.Regressiontest_changed_Job:   
    stage: RegressionTest
    before_script:
        - Xvfb :77 -extension RANDR -extension GLX & export DISPLAY=:77.0 &&
        - export PIP_CACHE_DIR="/opt/cache/pip"
        - source activate python36
        - pip install --upgrade git+https://github.com/MichaMans/BuildingsPy@testexamplescoverage
        - export PYTHONIOENCODING=utf-8 # just in case
    script:
        - model=$(git diff --raw --diff-filter=AMT HEAD^1)
        - echo $model >  bin/03_WhiteLists/changedmodels.txt
        - cd AixLib && python ../bin/02_CITests/UnitTests/runUnitTests.py -n 2 --batch --tool dymola --modified-models -s ${AixLib_package} -DS ${DymolaVersion}
    artifacts:
        paths:
          - AixLib/simulator-dymola.log
          - AixLib/unitTests-dymola.log
          - AixLib/failed-simulator-dymola.log
          - AixLib/funnel_comp/
          - AixLib/comparison-dymola.log
        expire_in: 7 day 
    retry:
        max: 2
        when: runner_system_failure
    except:
        - external_pull_requests
        - IBPSA_Merge 
    only:
        variables:
            - $CI_COMMIT_MESSAGE !~ /Correct HTML Code/
            - $CI_COMMIT_MESSAGE !~ /Trigger CI - Update reference results/ 
            - $CI_COMMIT_MESSAGE !~ /Trigger CI - give different reference results/
            - $CI_COMMIT_MESSAGE =~ /Trigger CI - Only Regressiontest/
            
        changes:
            - "AixLib/Resources/ReferenceResults/*${package}"
            - AixLib/${package}/**/*
            
 

Regression_changed_overall_coverage:
    stage: RegressionTest
    before_script:
        - Xvfb :77 -extension RANDR -extension GLX & export DISPLAY=:77.0 &&
        - export PIP_CACHE_DIR="/opt/cache/pip"
        - source activate python36
        - pip install --upgrade git+https://github.com/MichaMans/BuildingsPy@testexamplescoverage
        - export PYTHONIOENCODING=utf-8 # just in case
    script:
        - model=$(git diff --raw --diff-filter=AMT HEAD^1)
        - echo $model >  bin/03_WhiteLists/changedmodels.txt
        - cd AixLib && python ../bin/02_CITests/UnitTests/runUnitTests.py --coverage-only -DS ${DymolaVersion}
        - ls
    artifacts:
        when: on_failure
        paths:
            - AixLib/simulator-dymola.log
            - AixLib/unitTests-dymola.log
            - AixLib/funnel/
        expire_in: 7 day
    retry:
        max: 2
        when: runner_system_failure
    except:
        - external_pull_requests
        - IBPSA_Merge 
        
    only:
        variables:
            - $CI_COMMIT_MESSAGE !~ /Correct HTML Code/
            - $CI_COMMIT_MESSAGE !~ /Trigger CI - Update reference results/ 
            - $CI_COMMIT_MESSAGE !~ /Trigger CI - give different reference results/
        changes:
            - AixLib/**/*
   
            
            
    
            
Regressiontest_changed_AixLib_Airflow:
    variables:
        AixLib_package: AixLib.Airflow
        package : Airflow
    extends: .Regressiontest_changed_Job
       
Regressiontest_changed_AixLib_BoundaryConditions:
    variables:
        AixLib_package: AixLib.BoundaryConditions
        package : BoundaryConditions
    extends: .Regressiontest_changed_Job
           
Regressiontest_changed_AixLib_Controls:
    variables:
        AixLib_package: AixLib.Controls
        package : Controls
    extends: .Regressiontest_changed_Job
    
Regressiontest_changed_AixLib_Fluid:
    variables:
        AixLib_package: AixLib.Fluid
        package : Airflow
    extends: .Regressiontest_changed_Job
  
Regressiontest_changed_AixLib_Media:
    variables:
        AixLib_package: AixLib.Media
        package : Media
    extends: .Regressiontest_changed_Job
           

Regressiontest_changed_AixLib_Systems:
    variables:
        AixLib_package: AixLib.Systems
        package : Systems
    extends: .Regressiontest_changed_Job
 
Regressiontest_changed_AixLib_ThermalZones:
    variables:
        AixLib_package: AixLib.ThermalZones
        package : ThermalZones
    extends: .Regressiontest_changed_Job
    
  