#!/bin/bash

stages:
    - RegressionTest
    - prepare
   
    
 
.RegressionTest_Job:
    stage: RegressionTest
    before_script:
        - Xvfb :77 -extension RANDR -extension GLX & export DISPLAY=:77.0 &&
        - export PIP_CACHE_DIR="/opt/cache/pip"
        - source activate python36
        - pip install --upgrade git+https://github.com/MichaMans/BuildingsPy@testexamplescoverage
        - export PYTHONIOENCODING=utf-8 # just in case
        - echo 'FAIL' > bin/06_Configfiles/exit.sh

    script:
        - cd AixLib && python ../bin/02_CITests/UnitTests/runUnitTests.py -n 2 --batch --single-package ${AixLib_package} --tool dymola -DS ${DymolaVersion}
        - cd .. && echo 'successful' > bin/06_Configfiles/exit.sh

    after_script:
        - if cat bin/06_Configfiles/exit.sh | grep "FAIL"; then
            export PIP_CACHE_DIR="/opt/cache/pip" ;
            source activate python36 ;
            pip install pandas ;
            pip install mako ;
            pip install matplot ;
            python bin/02_CITests/Converter/google_charts.py --line-html --error --funnel-comp --single-package ${AixLib_package} ;
          else
            echo "Test was succesful!" ;
          fi
    artifacts:
        when: on_failure
        paths:
          - AixLib/simulator-dymola.log
          - AixLib/unitTests-dymola.log
          - bin/03_WhiteLists/charts/${AixLib_package}
        expire_in: 7 day
    retry:
        max: 2
        when: runner_system_failure
    only:
        - external_pull_requests
    except:
        variables:
            - $CI_COMMIT_MESSAGE  =~  /Correct HTML Code/  
            - $CI_COMMIT_MESSAGE  =~ /Trigger CI - Update reference results/
            - $CI_COMMIT_MESSAGE  =~ /Trigger CI - give different reference results/    

Regression_overall_coverage:
    stage: RegressionTest
    before_script:
        - export PIP_CACHE_DIR="/opt/cache/pip"
        - source activate python36
        - pip install --upgrade git+https://github.com/MichaMans/BuildingsPy@testexamplescoverage
        - export PYTHONIOENCODING=utf-8 # just in case
    script:
        - cd AixLib && python ../bin/02_CITests/UnitTests/runUnitTests.py --coverage-only -DS ${DymolaVersion}
    artifacts:
        when: on_failure
        paths:
            - AixLib/simulator-dymola.log
            - AixLib/unitTests-dymola.log
        expire_in: 7 day 
    retry:
        max: 2
        when: runner_system_failure
    only:
        - external_pull_requests
    except:
        variables:
            - $CI_COMMIT_MESSAGE  =~  /Correct HTML Code/  
            - $CI_COMMIT_MESSAGE  =~ /Trigger CI - Update reference results/
            - $CI_COMMIT_MESSAGE  =~ /Trigger CI - give different reference results/            

                      
            
Regressiontest_AixLib_Airflow:
    variables:
        AixLib_package: AixLib.Airflow
    extends: .RegressionTest_Job
           
Regressiontest_AixLib_BoundaryConditions:
    variables:
        AixLib_package: AixLib.BoundaryConditions
    extends: .RegressionTest_Job


Regressiontest_AixLib_Controls:
    variables:
        AixLib_package: AixLib.Controls
    extends: .RegressionTest_Job

Regressiontest_AixLib_Fluid:
    variables:
        AixLib_package: AixLib.Fluid
    extends: .RegressionTest_Job

Regressiontest_AixLib_Media:
    variables:
        AixLib_package: AixLib.Media
    extends: .RegressionTest_Job

Regressiontest_AixLib_Systems:
    variables:
        AixLib_package: AixLib.Systems
    extends: .RegressionTest_Job


Regressiontest_AixLib_ThermalZones:
    variables:
        AixLib_package: AixLib.ThermalZones
    extends: .RegressionTest_Job




prepare_plots:
    stage: prepare
    before_script:
        - Xvfb :77 -extension RANDR -extension GLX & export DISPLAY=:77.0 &&
        - export PIP_CACHE_DIR="/opt/cache/pip"
        - source activate python36
        - pip install --upgrade git+https://github.com/MichaMans/BuildingsPy@testexamplescoverage
        - pip install --upgrade pip
        - apt-get update -y
        - apt-get install zip unzip -y
        - pip install pandas
        - pip install mako
        - pip install requests
        - pip install matplot
        - export PYTHONIOENCODING=utf-8 # just in case
    script:
        - mkdir -p $CI_COMMIT_REF_NAME/plots 
        - python bin/02_CITests/Converter/google_charts.py  --create-layout
        - cp -r bin/03_WhiteLists/charts/* $CI_COMMIT_REF_NAME/plots 
        - python bin/02_CITests/Converter/PR_plot_regression_models.py --Working-Branch ${TARGET_BRANCH}  --GITLAB-Page ${GITLAB_Page} --GITHUB-TOKEN ${GITHUB_API_TOKEN} --GITHUB-REPOSITORY ${Github_Repository}
    artifacts:
        paths:
         - $CI_COMMIT_REF_NAME/plots 
         
        expire_in: 7h
    only:
        - external_pull_requests
   
    when: on_failure
    needs:
    - job: Regressiontest_AixLib_Airflow
      artifacts: true
    - job: Regressiontest_AixLib_BoundaryConditions
      artifacts: true
    - job: Regressiontest_AixLib_Controls
      artifacts: true
    - job: Regressiontest_AixLib_Fluid
      artifacts: true
    - job: Regressiontest_AixLib_Media
      artifacts: true
    - job: Regressiontest_AixLib_Systems
      artifacts: true
    - job: Regressiontest_AixLib_ThermalZones
      artifacts: true
        
        
        
      
        
        
        

  
