#!/bin/bash

stages:
    - Ref_Update
    - deploy
    
.Update_References_Job:
    stage: Ref_Update
    before_script:
        - Xvfb :77 -extension RANDR -extension GLX & export DISPLAY=:77.0 &&
        - export PIP_CACHE_DIR="/opt/cache/pip"
        - source activate python36  
        - python -V               # Print out python version for debugging
        - export PYTHONIOENCODING=utf-8 # just in case
        - pip install pandas
        - pip install mako
        - pip install matplot
    script:
        - cd AixLib && python ../bin/02_CITests/UnitTests/runUnitTests.py --single-package ${AixLib_package} --update-ref -DS ${DymolaVersion} --tool dymola -n 2  < ../bin/06_Configfiles/EOF.sh
        - python bin/02_CITests/Converter/google_charts.py --line-html --error --funnel-comp --single-package ${AixLib_package}
    artifacts:
        when: on_failure
        paths:
            - AixLib/simulator-dymola.log
            - AixLib/unitTests-dymola.log
            - AixLib/Resources/ReferenceResults/Dymola
            - New_Reference_Files
            - bin/03_WhiteLists/charts/${AixLib_package}
        expire_in: 7 day 
    except:
        - external_pull_requests
    only:
        variables:
            - $CI_COMMIT_MESSAGE  =~ /Trigger CI - Update reference results/
Airflow_Update_References:  
    variables:
        AixLib_package: AixLib.Airflow
    extends: .Update_References_Job
    
    
BoundaryConditions_Update_References:
    variables:
        AixLib_package: AixLib.BoundaryConditions
    extends: .Update_References_Job
   
Fluid_Update_References:
    variables:
        AixLib_package: AixLib.Fluid
    extends: .Update_References_Job

Systems_Update_References:
    variables:
        AixLib_package: AixLib.Systems
    extends: .Update_References_Job

ThermalZones_Update_References:
    variables:
        AixLib_package: AixLib.ThermalZones
    extends: .Update_References_Job

Controls_Update_References:
    variables:
        AixLib_package: AixLib.Controls
    extends: .Update_References_Job
    
    
Media_Update_References:
    variables:
        AixLib_package: AixLib.Media
    extends: .Update_References_Job

pages:
    stage: deploy
    before_script:
        - Xvfb :77 -extension RANDR -extension GLX & export DISPLAY=:77.0 &&
        - export PIP_CACHE_DIR="/opt/cache/pip"
        - source activate python36
        - pip install --upgrade git+https://github.com/MichaMans/BuildingsPy@testexamplescoverage
        - pip install --upgrade pip
        - apt-get update -y
        - apt-get install zip unzip -y
        - pip install pandas
        - pip install mako
        - pip install requests
        - pip install matplot
        - export PYTHONIOENCODING=utf-8 # just in case
    script:
        
        - mkdir -p public/$CI_COMMIT_REF_NAME
        - mkdir .public
        - mkdir -p $CI_COMMIT_REF_NAME
        - python bin/02_CITests/Converter/google_charts.py  --create-layout
        - cp -r bin/03_WhiteLists/charts/* $CI_COMMIT_REF_NAME
        - cp -r $CI_COMMIT_REF_NAME  public
       
    artifacts:
        paths:
         - public
         - AixLib/simulator-dymola.log
         - AixLib/unitTests-dymola.log
         - AixLib/funnel_comp
         - bin/03_WhiteLists/charts
        expire_in: 1h
    except:
        - external_pull_requests
    
    only:
        variables:
            - $CI_COMMIT_MESSAGE  =~ /Trigger CI - Update reference results/
    
    needs:
    - job: Airflow_Update_References
      artifacts: true

    - job: BoundaryConditions_Update_References
      artifacts: true

    - job: Controls_Update_References
      artifacts: true

    - job: Fluid_Update_References
      artifacts: true

    - job: Media_Update_References
      artifacts: true

    - job: Systems_Update_References
      artifacts: true

    - job: ThermalZones_Update_References
      artifacts: true

    when: on_failure
