#!/bin/bash

stages:
    - Simulate
 
.simulate_job:
    stage: Simulate
    before_script:
        - Xvfb :77 -extension RANDR -extension GLX & export DISPLAY=:77.0 &&
        - export PIP_CACHE_DIR="/opt/cache/pip"
        - source activate python36  
        - python -V               # Print out python version for debugging
        - export PYTHONIOENCODING=utf-8 # just in case
    script:
        - python bin/02_CITests/UnitTests/CheckPackages/validatetest.py -s "${AixLib_package}" -p AixLib/package.mo --SimulateExamples -DS ${DymolaVersion}
    artifacts:
        when: on_failure
        paths:
            - AixLib/${AixLib_package}-log.txt
            - AixLib/${AixLib_package}-Errorlog.txt
        expire_in: 7 day 
    only:
        - external_pull_requests  
    retry:
        max: 2
        when: runner_system_failure  
    except:
        variables:
            - $CI_COMMIT_MESSAGE  =~  /Correct HTML Code/ 
            - $CI_COMMIT_MESSAGE  =~ /Trigger CI - Update reference results/ 
            - $CI_COMMIT_MESSAGE  =~ /Trigger CI - give different reference results/ 

Simulate_AixLib_Airflow:
    variables:
        AixLib_package: AixLib.Airflow
    extends: .simulate_job

Simulate_AixLib_BoundaryConditions:
    variables:
        AixLib_package: AixLib.BoundaryConditions
    extends: .simulate_job
    
Simulate_AixLib_Controls:
    variables:
        AixLib_package: AixLib.Controls
    extends: .simulate_job
    
Simulate_AixLib_Electrical:
    variables:
        AixLib_package: AixLib.Electrical
    extends: .simulate_job            
     
Simulate_AixLib_Fluid:
    variables:
        AixLib_package: AixLib.Fluid
    extends: .simulate_job
    
Simulate_AixLib_Media:
    variables:
        AixLib_package: AixLib.Media
    extends: .simulate_job           


Simulate_AixLib_ThermalZones:
    variables:
        AixLib_package: AixLib.ThermalZones
    extends: .simulate_job         
    
  