# configuration file for automatic issue branch creation

#branchName: 'Issue${issue.number}_${issue.title}'
branchName: 'Issue${issue.number}_${SHORT_NAME}'
 silent: false
autoCloseIssue: true
gitSafeReplacementChar: '-'

branches:
  - label: question
    skip: true