#!/bin/bash
image: registry.git.rwth-aachen.de/ebc/ebc_intern/dymola-docker:fixbugs_dymola2021-miniconda

stages:
    - deleteBranch
    - IBPSA_Merge
    - Update_WhiteList
    - Release
    - SetSettings
    - CheckSettings
    - Ref_Check
    - Ref_Update
    - Dif_Ref
    - build
    - HTMLCheck
    - deploy
    - openMR
    - post
    - ChangedModels
    - StyleCheck
    - Check
    - Simulate
    - RegressionTest
 
variables:
    Praefix_Branch: "Correct_HTML_"
    TARGET_BRANCH: $CI_COMMIT_REF_NAME
    Newbranch: ${Praefix_Branch}${CI_COMMIT_REF_NAME}
    Github_Repository : SvenHinrichs/GitLabCI
    
    
include:
  - project: 'SvenHinrichs/GitLabCI'
    file:  'bin/05_Templates/CheckConfiguration/check_settings.gitlab-ci.yml'
  - project: 'SvenHinrichs/GitLabCI'
    file:  'bin/05_Templates/CheckConfiguration/deploy_ref.gitlab-ci.yml'
  - project: 'SvenHinrichs/GitLabCI'
    file:  'bin/05_Templates/deploy/IBPSA_Merge.gitlab-ci.yml'
  - project: 'SvenHinrichs/GitLabCI'
    file:  'bin/05_Templates/UnitTests/regression_ref_check.gitlab-ci.yml'
  - project: 'SvenHinrichs/GitLabCI'
    file:  'bin/05_Templates/SyntaxTests/html_check.gitlab-ci.yml'
  - project: 'SvenHinrichs/GitLabCI'
    file:  'bin/05_Templates/SyntaxTests/style_check.gitlab-ci.yml'
  - project: 'SvenHinrichs/GitLabCI'
    file:  'bin/05_Templates/UnitTests/check_model.gitlab-ci.yml'
  - project: 'SvenHinrichs/GitLabCI'
    file:  'bin/05_Templates/UnitTests/regression_test.gitlab-ci.yml'
  - project: 'SvenHinrichs/GitLabCI'
    file:  'bin/05_Templates/UnitTests/simulate_model.gitlab-ci.yml'
  - project: 'SvenHinrichs/GitLabCI'
    file:  'bin/05_Templates/UnitTests/changed_simulate_model.gitlab-ci.yml'
  - project: 'SvenHinrichs/GitLabCI'
    file:  'bin/05_Templates/UnitTests/changed_check_model.gitlab-ci.yml'
  - project: 'SvenHinrichs/GitLabCI'
    file: 'bin/05_Templates/UnitTests/changed_regression_test.gitlab-ci.yml'

 
  
  
