image: registry.git.rwth-aachen.de/ebc/ebc_intern/dymola-docker:miniconda-latest
stages:
    - check

.check_changed_models_job:
    stage: check
    variables:
        package_name: $package
    before_script:
        - Xvfb :77 -extension RANDR -extension GLX & export DISPLAY=:77.0 &&
        - export PIP_CACHE_DIR="/opt/cache/pip"
        - source activate python36
        - export PYTHONIOENCODING=utf-8 # just in case
    script:
        - model=$(git diff --raw --diff-filter=AMT HEAD^1)
        - echo $model >  bin/03_Whitelists/changedmodels.txt
        - python bin/02_CITests/UnitTests/CheckPackages/validatetest.py --single-package $package --library AixLib -DS 2020 -CM 
    artifacts:
        when: on_failure
        paths:
            - AixLib/$package-log.txt
            - AixLib/$package-Errorlog.txt
            - bin/03_Whitelists/changedmodels.txt
        expire_in: 7 day
    except:
        - external_pull_requests
        - IBPSA_Merge
    only:
        changes:
            - $lib_package/**/*
    retry:
        max: 2
        when: runner_system_failure



Check_AixLib_Airflow_changed_models:
    variables:
        lib_package: AixLib/Airflow
        package: Airflow  
    extends: .check_changed_models_job

Check_AixLib_BoundaryConditions_changed_models:
    variables:
        lib_package: AixLib/BoundaryConditions
        package: BoundaryConditions  
    extends: .check_changed_models_job

Check_AixLib_Controls_changed_models:
    variables:
        lib_package: AixLib/Controls
        package: Controls  
    extends: .check_changed_models_job

Check_AixLib_Electrical_changed_models:
    variables:
        lib_package: AixLib/Electrical
        package: Electrical  
    extends: .check_changed_models_job

Check_AixLib_Fluid_changed_models:
    variables:
        lib_package: AixLib/Fluid
        package: Fluid  
    extends: .check_changed_models_job

Check_AixLib_ThermalZones_changed_models:
    variables:
        lib_package: AixLib/ThermalZones
        package: ThermalZones  
    extends: .check_changed_models_job
 
