#!/bin/bash
image: registry.git.rwth-aachen.de/ebc/ebc_intern/dymola-docker:miniconda-latest

stages:
    - compile
    - log
    - post

 
 
 
variables:
    Praefix_Branch: "Correct_HTML_"
    TARGET_BRANCH: $CI_COMMIT_REF_NAME
    Newbranch: ${Praefix_Branch}${CI_COMMIT_REF_NAME}
    StyleModel: AixLib.Airflow.Multizone.DoorDiscretizedOpen
    Github_Repository : SvenHinrichs/GitLabCI
 
 
include:
  - project: 'SvenHinrichs/GitLabCI'
    file:  'bin/05_Templates/Pages/gitlab-page.gitlab-ci.yml'
