#!/bin/bash
image: registry.git.rwth-aachen.de/ebc/ebc_intern/dymola-docker:miniconda-latest

stages:
    - deleteBranch
    - SetSettings
    - CheckSettings
    - build
    - HTMLCheck
    - deploy
    - openMR
    - post
    - StyleCheck
    - Check
    - Simulate
    - RegressionTest
 
variables:
    Praefix_Branch: "Correct_HTML_"
    TARGET_BRANCH: $CI_COMMIT_REF_NAME
    Newbranch: ${Praefix_Branch}${CI_COMMIT_REF_NAME}
    Github_Repository : SvenHinrichs/GitLabCI
    
include:
  - project: 'EBC/EBC_all/gitlab_ci/templates'
    file:  'modelica-ci-tests/CheckConfiguration/check_settings.gitlab-ci.yml'
  
  
