#!/bin/bash
image: registry.git.rwth-aachen.de/ebc/ebc_intern/dymola-docker:miniconda-latest

stages:
    - deleteBranch
    - plot_regressiontest
    - log
    - pages
    - IBPSA_Merge
    - Update_WhiteList
    - Release
    - SetSettings
    - CheckSettings
    - Ref_Check
    - Ref_Update
    - Dif_Ref
    - build
    - HTMLCheck
    - openMR
    - post
    - ChangedModels
    - StyleCheck
    - Check
    - Simulate
    - RegressionTest
    - deploy
    
variables:
    Praefix_Branch: "Correct_HTML_"
    TARGET_BRANCH: $CI_COMMIT_REF_NAME
    Newbranch: ${Praefix_Branch}${CI_COMMIT_REF_NAME}
    Github_Repository : SvenHinrichs/GitLabCI
    GITLAB_Page: "https://svenhinrichs.pages.rwth-aachen.de/GitLabCI/"


include:
  - project: 'SvenHinrichs/GitLabCI'
    file:  'bin/05_Templates/UnitTests/regression_test.gitlab-ci.yml'


 
  
  
