
image: registry.git.rwth-aachen.de/ebc/ebc_intern/dymola-docker:miniconda-latest

stages:
    - CheckSettings
    - build
    - HTMLCheck
    - deploy
    - openMR
    - post
    - StyleCheck
    - Check
    - Simulate
    - RegressionTest


variables:
    TARGET_BRANCH: "{$CI_BUILD_REF_NAME#Correct_HTML_}"
    Newbranch: "Correct_HTML_$TARGET_BRANCH"
    StyleModel: AixLib.Airflow.Multizone.DoorDiscretizedOpen

include:
  - project: 'sven.hinrichs/GitLabCI'
    file:  'bin/05_Templates/CheckConfiguration/check_settings.gitlab-ci.yml'
  - project: 'sven.hinrichs/GitLabCI'
    file:  'bin/05_Templates/SyntaxTests/html_check.gitlab-ci.yml'
  - project: 'sven.hinrichs/GitLabCI'
    file:  'bin/05_Templates/SyntaxTests/style_check.gitlab-ci.yml'
  - project: 'sven.hinrichs/GitLabCI'
    file: 'bin/05_Templates/UnitTests/check_model.gitlab-ci.yml'
  - project: 'sven.hinrichs/GitLabCI'
    file: 'bin/05_Templates/UnitTests/regression_test.gitlac-ci.yml'
  - project: 'sven.hinrichs/GitLabCI'
    file: 'bin/05_Templates/UnitTests/simulate_model.gitlab-ci.yml'
  