image: registry.git.rwth-aachen.de/ebc/ebc_intern/dymola-docker:miniconda-latest

stages:
    - compile
    - log
    - post
    
variables:
    TARGET_BRANCH: master
    Newbranch: "Correct_HTML_$TARGET_BRANCH"
    StyleModel: AixLib.Airflow.Multizone.DoorDiscretizedOpen

include:
  - project: 'EBC/EBC_all/gitlab_ci/templates'
    file: '/pylint/pylint.gitlab-ci.yml'
 