#!/bin/bash
image: registry.git.rwth-aachen.de/ebc/ebc_intern/dymola-docker:miniconda-latest
stages:
    - deleteBranch
    - plot_regressiontest
    - log
    - pages
    - IBPSA_Merge
    - Update_WhiteList
    - Release
    - SetSettings
    - CheckSettings
    - Ref_Check
    - Ref_Update
    - Dif_Ref
    - build
    - HTMLCheck
    - openMR
    - post
    - ChangedModels
    - StyleCheck
    - Check
    - Simulate
    - RegressionTest
    - prepare
    - deploy
    
variables:
    Praefix_Branch: "Correct_HTML_"
    TARGET_BRANCH: $CI_COMMIT_REF_NAME
    Newbranch: ${Praefix_Branch}${CI_COMMIT_REF_NAME}
    Github_Repository : SvenHinrichs/GitLabCI
    GITLAB_Page: "https://svenhinrichs.pages.rwth-aachen.de/GitLabCI/"
    Merge_Branch: "IBPSA_Merge"
    
IBPSA:
    stage: IBPSA_Merge
    before_script:
        - Xvfb :77 -extension RANDR -extension GLX & export DISPLAY=:77.0 &&
        - export PIP_CACHE_DIR="/opt/cache/pip"
        - source activate python36  
        - python -V               # Print out python version for debugging
        - export PYTHONIOENCODING=utf-8 # just in case
        - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
        - eval $(ssh-agent -s)
        - mkdir -p ~/.ssh
        - ssh-keyscan github.com >> ~/.ssh/known_hosts
        - ssh-agent -a /tmp/ssh_agent.sock > /dev/null
        - echo "${GITHUB_PRIVATE_KEY}" > ~/.ssh/id_rsa
        - chmod 600 ~/.ssh/id_rsa
        - git config --global user.name "${GITLAB_USER_NAME}" 
        - git config --global user.email "${GITLAB_USER_EMAIL}"
        
      
    script:
        # Clone IBPSA
        - mkdir Merge_Package
        - cd Merge_Package
        - git clone --single-branch --branch  ${Merge_Branch} git@github.com:${Github_Repository}.git
        # Execute IBPSA MERGE SKRIPT
        - ls 
        - cd ${CI_PROJECT_NAME}
        - ls 
        - git clone ${IBPSA_Repo}
        - cd AixLib/Resources/Scripts
        - python mergeModelicaIBPSA.py
        - cd ..
        - cd ..
        - cd .. 
        # Copy Convert mos
        - python bin/02_CITests/deploy/IBPSA_Merge/copy_conversion_script.py --dst "Convertmos" --ibpsa-dir  "modelica-ibpsa/IBPSA/Resources/Scripts/Dymola/ConvertIBPSA_*" --aixlib-dir "AixLib/Resources/Scripts"
        # Delte Userguide from package.order
        - python bin/02_CITests/deploy/IBPSA_Merge/correct_userguide.py
        # git checkout -B ${Merge_Branch}
        - rm -r modelica-ibpsa
        
           
    only:
        - IBPSA_Merge
    except:   
        refs:
            -  external_pull_requests
        variables:
            - $CI_COMMIT_MESSAGE =~ /Update WhiteList_CheckModel.txt and HTML_IBPSA_WhiteList.txt/    
            - $CI_COMMIT_MESSAGE =~ /CI - Create IBPSA Merge/
            - $CI_COMMIT_MESSAGE =~ /Automatic push of CI with new regression reference files. Please pull the new files before push again./
            - $CI_COMMIT_MESSAGE =~ /fix errors manually/
            - $CI_COMMIT_MESSAGE =~/Trigger CI - give different reference results/
            - $CI_COMMIT_MESSAGE  =~ /Trigger CI - Update reference results/


    
    artifacts:
        paths:
            - Merge_Package/GitLabCI/
        expire_in: 6 h     

WhiteList:
    
    stage: Update_WhiteList
    before_script:
        - Xvfb :77 -extension RANDR -extension GLX & export DISPLAY=:77.0 &&
        - export PIP_CACHE_DIR="/opt/cache/pip"
        - source activate python36  
        - python -V               # Print out python version for debugging
        - export PYTHONIOENCODING=utf-8 # just in case
        - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
        - eval $(ssh-agent -s)
        - mkdir -p ~/.ssh
        - ssh-keyscan github.com >> ~/.ssh/known_hosts
        - ssh-agent -a /tmp/ssh_agent.sock > /dev/null
        - echo "${GITHUB_PRIVATE_KEY}" > ~/.ssh/id_rsa
        - chmod 600 ~/.ssh/id_rsa
        - git config --global user.name "${GITLAB_USER_NAME}" 
        - git config --global user.email "${GITLAB_USER_EMAIL}"
        
      
    script:
        - cd Merge_Package/${CI_PROJECT_NAME}
        # Update WhiteList for HTML
        - python bin/02_CITests/SyntaxTests/html_tidy_errors.py --WhiteList
        ## Update WhiteList for CheckPackages
        - python bin/02_CITests/UnitTests/CheckPackages/validatetest.py --WhiteList -DS ${DymolaVersion} -s AixLib
        - python bin/02_CITests/Converter/ibpsa_icon.py
        - rm  -r IBPSA
        - message="Update WhiteList_CheckModel.txt and HTML_IBPSA_WhiteList.txt"
        - git add  . 
        - git commit -m "$message" 
        - git push --force git@github.com:${Github_Repository}.git
           
    only:
        - IBPSA_Merge
    except:   
        refs: 
            - external_pull_requests
        variables:
            - $CI_COMMIT_MESSAGE =~ /Update WhiteList_CheckModel.txt and HTML_IBPSA_WhiteList.txt/    
            - $CI_COMMIT_MESSAGE =~ /CI - Create IBPSA Merge/
            - $CI_COMMIT_MESSAGE =~ /Automatic push of CI with new regression reference files. Please pull the new files before push again./
            - $CI_COMMIT_MESSAGE =~ /fix errors manually/
            - $CI_COMMIT_MESSAGE =~/Trigger CI - give different reference results/
            - $CI_COMMIT_MESSAGE  =~ /Trigger CI - Update reference results/
    allow_failure: true
    
    needs:
    - job: IBPSA
      artifacts: true
    

IBPSA_Pull_Request:
    stage: openMR
    only:
        - /^feature\/*/
    before_script:
        - sudo apt-get install jq -y
        - pip install requests
        - git config --global user.name "${GITLAB_USER_NAME}" 
        - git config --global user.email "${GITLAB_USER_EMAIL}"
  
    script:
       - python bin/02_CITests/deploy/IBPSA_Merge/PR_IPBSA_Merge.py --GITHUB-REPOSITORY ${Github_Repository} --Working-Branch ${Target_Branch} --Correct-Branch ${Merge_Branch} --GITHUB-TOKEN ${GITHUB_API_TOKEN}
    only:
        - IBPSA_Merge
    except:    
        refs: 
            - external_pull_requests
        variables:
            - $CI_COMMIT_MESSAGE =~ /Update WhiteList_CheckModel.txt and HTML_IBPSA_WhiteList.txt/    
            - $CI_COMMIT_MESSAGE =~ /CI - Create IBPSA Merge/
            - $CI_COMMIT_MESSAGE =~ /Automatic push of CI with new regression reference files. Please pull the new files before push again./
            - $CI_COMMIT_MESSAGE =~ /fix errors manually/
            - $CI_COMMIT_MESSAGE =~/Trigger CI - give different reference results/
            - $CI_COMMIT_MESSAGE  =~ /Trigger CI - Update reference results/
   