#!/bin/bash

image: registry.git.rwth-aachen.de/ebc/ebc_intern/dymola-docker:miniconda-latest

stages:
    - RegressionTest
    
.Regressiontest_job:
    stage: RegressionTest
    before_script:
        - Xvfb :77 -extension RANDR -extension GLX & export DISPLAY=:77.0 &&
        - export PIP_CACHE_DIR="/opt/cache/pip"
        - source activate python36
        - pip install --upgrade git+https://github.com/MichaMans/BuildingsPy@testexamplescoverage
        - export PYTHONIOENCODING=utf-8 # just in case
        - echo 'FAIL' > bin/06_Configfiles/exit.sh
    script:
        - cd AixLib && python ../bin/02_CITests/UnitTests/reference_check.py --single-package "${lib_package}" --library AixLib --batch -DS 2929
        - cd .. && echo 'successful' > bin/06_Configfiles/exit.sh
    after_script:
        - if cat bin/06_Configfiles/exit.sh | grep "FAIL"; then
            export PIP_CACHE_DIR="/opt/cache/pip";
            source activate python36;
            pip install pandas mako matplot;
            python bin/02_CITests/Converter/google_charts.py --line-html --error --funnel-comp --single-package ${lib_package};
          else
            echo "Test was succesful!";
          fi
    artifacts:
        when: on_failure
        paths:
          - AixLib/simulator-dymola.log
          - AixLib/unitTests-dymola.log
          - AixLib/failed-simulator-dymola.log
          - AixLib/funnel_comp/
          - AixLib/comparison-dymola.log
          - bin/07_templates/02_charts/${lib_package}
        expire_in: 7 day
    only:
        refs:
            - external_pull_requests
    except:
        variables:
            - $CI_COMMIT_MESSAGE  =~ /ci_update_ref/
            - $CI_COMMIT_MESSAGE  =~ /ci_dif_ref/
            - $CI_COMMIT_MESSAGE  =~ /ci_correct_html/
            - $CI_COMMIT_MESSAGE  =~ /ci_create_whitelist/
            - $CI_COMMIT_MESSAGE  =~ /Update WhiteList_CheckModel.txt and HTML_IBPSA_WhiteList.txt/
            - $CI_COMMIT_MESSAGE  =~ /Automatic push of CI with new regression reference files. Please pull the new files before push again./
            - $CI_COMMIT_MESSAGE  =~ /New reference files were pushed to this branch. The job was successfully and the newly added files are tested in another commit./
    retry:
        max: 2
        when: runner_system_failure
    
Regressiontest_AixLib_Airflow:
    variables:
        lib_package: AixLib.Airflow
    extends: .Regressiontest_job

Regressiontest_AixLib_BoundaryConditions:
    variables:
        lib_package: AixLib.BoundaryConditions
    extends: .Regressiontest_job

Regressiontest_AixLib_Controls:
    variables:
        lib_package: AixLib.Controls
    extends: .Regressiontest_job



prepare_create_plots:
    stage: prepare
    before_script:
        - source activate python36
        - pip install --upgrade git+https://github.com/MichaMans/BuildingsPy@testexamplescoverage
        - pip install --upgrade pip &&  apt-get update -y && apt-get install zip unzip -y
        - pip install pandas mako matplot
        - export PYTHONIOENCODING=utf-8 # just in case
    script:
        - mkdir -p $CI_COMMIT_REF_NAME/plots
        - python bin/02_CITests/Converter/google_charts.py  --create-layout
        - cp -r bin/07_templates/02_charts/* $CI_COMMIT_REF_NAME/plots
        - python bin/02_CITests/api_script/github_api.py --prepare-plots --working-branch ${TARGET_BRANCH} --github-repo ${Github_Repository} --gitlab-page ${GITLAB_Page} --github-token ${GITHUB_API_TOKEN} 
    artifacts:
        paths:
         - $CI_COMMIT_REF_NAME/plots
    only:
        refs:
            - external_pull_requests
    except:
        variables:
            - $CI_COMMIT_MESSAGE  =~ /ci_update_ref/
            - $CI_COMMIT_MESSAGE  =~ /ci_dif_ref/
            - $CI_COMMIT_MESSAGE  =~ /ci_correct_html/
            - $CI_COMMIT_MESSAGE  =~ /ci_create_whitelist/
            - $CI_COMMIT_MESSAGE  =~ /Update WhiteList_CheckModel.txt and HTML_IBPSA_WhiteList.txt/
            - $CI_COMMIT_MESSAGE  =~ /Automatic push of CI with new regression reference files. Please pull the new files before push again./
            - $CI_COMMIT_MESSAGE  =~ /New reference files were pushed to this branch. The job was successfully and the newly added files are tested in another commit./
    when: on_failure
    needs:
    - job: Regressiontest_AixLib_Airflow
      artifacts: true
    - job: Regressiontest_AixLib_BoundaryConditions
      artifacts: true
    - job: Regressiontest_AixLib_Controls
      artifacts: true


