#!/bin/bash
image: registry.git.rwth-aachen.de/ebc/ebc_intern/dymola-docker:miniconda-latest
stages:
    - SetSettings
    - modelica_Check

test_fmt:
    stage: SetSettings
    services:
        - docker
    before_script:
        # cd modelica-fmt 
        - sudo apt-get install docker
        - sudo apt-get install git 
        - sudo apt-get install wget
        - wget https://dl.google.com/go/go1.11.1.linux-amd64.tar.gz
        - sudo tar -C /usr/local -xzf go1.11.1.linux-amd64.tar.gz
        - export PATH=$PATH:/usr/local/go/bin:${HOME}/go/bin
        - source ~/.bashrc
        - go env
        - go version
        - go build -o modelicafmt
        # go build -o bin/02_CITests/SyntaxTests/modelica-fmt/modelicafmt.go
        # sudo chmod +x bin/02_CITests/SyntaxTests/modelica-fmt/generate_parser.sh
        # bin/02_CITests/SyntaxTests/modelica-fmt/generate_parser.sh
    script:
        - cd bin/02_CITests/SyntaxTests/modelica-fmt
        - ./modelica-fmt examples/gmt-building.mo > examples/gmt-building-out.mo
      
    
Modelica_fmt:
    stage: modelica_Check
    services:
        -  docker
    before_script:
        - sudo apt install linuxbrew-wrapper -y
        - brew install go
        - go build -o modelicafmt
        - bin/02_CITests/SyntaxTests/modelica-fmt/generate_parser.sh
    script:
        - cd bin/02_CITests/SyntaxTests/modelica-fmt
        - ./modelica-fmt examples/gmt-building.mo > examples/gmt-building-out.mo
    
   