stages:
- pages
- log


pages:
    stage: deploy
    before_script:
        - export PIP_CACHE_DIR="/opt/cache/pip"
        - pip install pandas
        - source activate python36
        - pip install --upgrade git+https://github.com/MichaMans/BuildingsPy@testexamplescoverage
        - export PYTHONIOENCODING=utf-8 # just in case
    script:
        - cd AixLib && python ../bin/02_CITests/UnitTests/runUnitTests.py -n 2 --batch --single-package AixLib.Airflow --tool dymola -DS ${DymolaVersion}
        - cd ..
        - python bin/02_CITests/Converter/google_charts.py --line-html --error --funnel-comp
        - mkdir -p .public/$CI_COMMIT_REF_NAME
        - cp -r * .public/$CI_COMMIT_REF_NAME
        - mv .public public/$CI_COMMIT_REF_NAME
        
    artifacts:
        paths:
         - public
         - AixLib/simulator-dymola.log
         - AixLib/unitTests-dymola.log
         - AixLib/funnel_comp
         - bin/03_WhiteLists/charts


