stages:
- pages
- deploy


pages:
    stage: deploy
    before_script:
        - Xvfb :77 -extension RANDR -extension GLX & export DISPLAY=:77.0 &&
        - export PIP_CACHE_DIR="/opt/cache/pip"
        - source activate python36
        - pip install --upgrade git+https://github.com/MichaMans/BuildingsPy@testexamplescoverage
        - pip install --upgrade pip
        - pip install pandas
        - pip install mako
        - export PYTHONIOENCODING=utf-8 # just in case
    script:
        # cd AixLib && python ../bin/02_CITests/UnitTests/runUnitTests.py -n 2 --batch --single-package AixLib.Airflow --tool dymola -DS ${DymolaVersion}
        # cd ..
        - mkdir public
        - python bin/02_CITests/Converter/google_charts.py --line-html --error --funnel-comp
        - ls
        - cp bin/03_WhiteLists/charts/* public
        - mv .public public
       
        
    artifacts:
        when: on_failure
        paths:
         - public
         - AixLib/simulator-dymola.log
         - AixLib/unitTests-dymola.log
         - AixLib/funnel_comp
         - bin/03_WhiteLists/charts
        expire_in: 1h



pages_issues:
# Page to generate content to be downloaded in the artifact-section.
  stage: deploy
  before_script:
    - apt-get update -y
    - apt-get install zip unzip -y
    - apt-get install curl -y
  script:
    - set +e
    - curl --fail --header "PRIVATE-TOKEN:$GL_TOKEN" $CI_PAGES_URL/content.zip -o content.zip
    - if [ -e "content.zip" ]; then unzip "content.zip"; rm "content.zip"; fi
    - set -e
    # Add/update content
    # TODO: mv $CI_COMMIT_REF_NAME/* to public/$CI_COMMIT_REF_NAME/*
    - mkdir -p public/$CI_COMMIT_REF_NAME
    - cp -r $CI_COMMIT_REF_NAME/* public/$CI_COMMIT_REF_NAME
    # Zip the content and publish the zip again
    - zip -r "content.zip" "public"
    - mv "content.zip" "public/"
  artifacts:
    paths:
      - public
      # Make the minor documentation expire in a reasonable development time
    expire_in: 2 weeks
