stages:
- pages
- deploy

variables:
    GITLAB_Page: "https://svenhinrichs.pages.rwth-aachen.de/GitLabCI/"


pages:
    stage: deploy
    before_script:
        - Xvfb :77 -extension RANDR -extension GLX & export DISPLAY=:77.0 &&
        - export PIP_CACHE_DIR="/opt/cache/pip"
        - source activate python36
        - pip install --upgrade git+https://github.com/MichaMans/BuildingsPy@testexamplescoverage
        - pip install --upgrade pip
        - pip install pandas
        - pip install mako
        - pip install requests
        - export PYTHONIOENCODING=utf-8 # just in case
    script:
        # cd AixLib && python ../bin/02_CITests/UnitTests/runUnitTests.py -n 2 --batch --single-package AixLib.Airflow --tool dymola -DS ${DymolaVersion}
        # cd ..
        - python bin/02_CITests/Converter/google_charts.py --line-html --error --funnel-comp

        - mkdir .public
        - mkdir -p public/$CI_COMMIT_REF_NAME
        - cp -r $CI_COMMIT_REF_NAME/* public/$CI_COMMIT_REF_NAME
        # cp -r bin/03_WhiteLists/charts/* .public
        # mv .public public/$CI_COMMIT_REF_NAME
        - python bin/02_CITests/Converter/PR_plot_regression_models.py --Working-Branch ${TARGET_BRANCH}  --GITLAB-Page ${GITLAB_Page} --GITHUB-TOKEN ${GITHUB_API_TOKEN} --GITHUB-REPOSITORY ${Github_Repository}
        
    artifacts:
        paths:
         - public
         - AixLib/simulator-dymola.log
         - AixLib/unitTests-dymola.log
         - AixLib/funnel_comp
         - bin/03_WhiteLists/charts
        expire_in: 1h




