#!/bin/bash
image: registry.git.rwth-aachen.de/ebc/ebc_intern/dymola-docker:miniconda-latest

stages:
    - ChangedModels


Check_Model_Change:
    stage: ChangedModels
    services:
        - docker
    script:
        - model=$(git diff --raw HEAD^1)
        - echo $model
        - echo $model >  bin/03_WhiteLists/changed_model.sh
        - if cat bin/06_Configfiles/changed_model.sh | grep ".mo"; then
            echo "Modelica .mo Models was changed in last Push";
            echo "Start CI Tests for changed models";
            exit 0;
          else
            echo "No Modelica .mo Models was changed";
            echo "Skip CI Tests";
            exit 2;
          fi
    #allow_failure: true  
    except:
        - external_pull_requests
    only:
        variables:
            - $CI_COMMIT_MESSAGE !~ /Correct HTML Code/