#!/bin/bash

stages:
    - SetSettings


Settings:
    stage: SetSettings
    services:
        -  docker
    before_script:
        - sudo apt-get install jq -y
    
    script:
        - sudo chmod +x bin/06_Configfiles/SetSettings.sh
        - bin/06_Configfiles/SetSettings.sh
       
    
    

